// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	streams "github.com/msales/streams/v6"
	mock "github.com/stretchr/testify/mock"
)

// Predicate is an autogenerated mock type for the Predicate type
type Predicate struct {
	mock.Mock
}

// Assert provides a mock function with given fields: _a0
func (_m *Predicate) Assert(_a0 streams.Message) (bool, error) {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(streams.Message) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(streams.Message) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
