name: Test

on: push

env:
  GO111MODULE: on

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.17','1.18','1.19','1.20','1.21', '1.21.x' ]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Install cover
        run: go get -u golang.org/x/tools/cmd/cover

      - name: Install vet
        run: go get -u github.com/mattn/goveralls

      - name: Install goveralls
        run: go get -u github.com/mattn/goveralls

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -race -bench=. -covermode=atomic -coverprofile=profile_full.cov -coverpkg=github.com/msales/streams/... ./...

      - name: Goveralls
        run: |
          cat profile_full.cov | grep -v .pb.go | grep -v mock | grep -v test > profile.cov;
          goveralls -coverprofile=profile.cov -service=github || true;

